### PR TITLE
Check for null WP_REST_Request content type.

### LINKED ISSUE #5: NOTICE: PHP message: PHP Notice:  Trying to access array offset on value of type null
If a request isn't set (edge case) the value of content type doesn't exist.

> NOTICE: PHP message: PHP Notice:  Trying to access array offset on value of type null in /usr/local/wordpress/vendor/ironbound/wp-rest-api-schema-validator/src/Middleware.php on line 830

https://github.com/iron-bound-designs/wp-rest-api-schema-validator/blob/c5452e3ae972a13a1581a219c96c4cf1c81d5e60/src/Middleware.php#L830

### PR DESCRIPTION
**Pull request by thefrosty**
Fixes #5

### CODE REVIEW

**Comment by TimothyBJacobs** [comment]
Thanks for the PR! To answer your question from the issue, the content-type must be set to JSON for it to be treated as JSON, by default we just treat it as regular post variables.

When I originally wrote this, though, `WP_REST_Request::set_param` didn't have its logic updated to properly handle setting the value in the correct "slot". That got fixed in 4.8, so we could probably drop this method entirely and just call `WP_REST_Request::set_param` directly.

**Comment by thefrosty** [comment]
Let me know which you prefer.

**Comment by TimothyBJacobs** [comment]
Yeah let's just call the Core method directly.

**Comment by TimothyBJacobs** [comment]
Thanks for the patch!

**Pull request merged**
